<a href="https://colab.research.google.com/github/baaaRaathh/Machine-Learning/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_openml

In [ ]:
boston = fetch_openml(data_id=506)

feature = boston['data']
traget = boston['target']

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:1022: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(

In [ ]:
feature

,Married,Age,Years_of_education,Male,Religious,Sex_partners,Income,Drug_use,Same_sex_relations
0,1,52,14,0,1,1,32500.0,0,0
1,0,58,16,0,1,0,21250.0,0,0
2,0,22,14,1,1,15,2000.0,0,0
3,1,35,14,1,1,5,21250.0,0,0
4,0,43,20,1,1,1,67500.0,0,0
...,...,...,...,...,...,...,...,...,...
154,1,41,19,1,0,1,27500.0,0,0
155,1,29,14,0,1,1,27500.0,0,0
156,0,45,12,1,1,1,16250.0,0,0
157,1,35,12,1,1,1,55000.0,0,0
158,1,47,12,0,1,1,500.0,0,0

In [ ]:
traget

0      0
1      2
2      0
3      0
4      0
      ..
154    0
155    0
156    0
157    0
158    1
Name: AIDS_know, Length: 159, dtype: int64